---
sidebar: sidebar 
permalink: doc-gen-ai-assistant.html 
keywords: netapp, generative ai, doc 
summary: 'Doc est notre assistant génératif optimisé par l"IA sur docs.netapp.com. Doc est conçu pour répondre aux questions relatives aux produits NetApp, à l"aide du contenu publié sur docs.NetApp.com.' 
---
= Présentation de l'assistant génératif NetApp optimisé par l'IA
:hardbreaks:
:allow-uri-read: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Doc est notre assistant génératif optimisé par l'IA sur docs.netapp.com. Doc est conçu pour répondre aux questions relatives aux produits NetApp, à l'aide du contenu publié sur docs.NetApp.com.

Le DOC peut créer des réponses à partir de questions précédentes, suggérer des questions supplémentaires et expliquer comment il génère des réponses. Cela en fait un outil précieux pour naviguer dans la documentation NetApp.



== Portée et limites

Doc ne peut répondre qu'aux questions en fonction du contenu publié sur docs.NetApp.com.

* Doc répond aux questions en se basant uniquement sur la dernière version publiée d'un produit. Par exemple, s'il existe une documentation pour les versions 1.0 et 2.0 d'un produit, Doc se réfère uniquement à la documentation 2.0 la plus récente.
* Pour de meilleurs résultats, soyez toujours précis dans les noms de produits. Doc sait sur quelle page vous vous trouvez lorsque vous posez une question, mais ce n'est qu'un facteur parmi d'autres qu'il prend en compte pour formuler une réponse.
* Doc peut discuter dans les langues prises en charge sur docs.NetApp.com, mais n'est pas formé sur les versions non anglaises.




== Rédaction de bons messages-guides

Suivez ces conseils pour une expérience optimale avec Doc

Posez des questions spécifiques.:: Rédigez des questions détaillées et spécifiez le nom du produit, la version et le type d'interface (interface graphique, API). Par exemple :
+
--
[]
====
Quelles étapes dois-je suivre dans System Manager pour effectuer la mise à niveau de ONTAP 9.8 vers ONTAP 9.12.1 ?

====
--
Demandez des étapes pour effectuer une tâche.:: Demandez au Doc d’inclure les étapes pour terminer un processus.  Au lieu de demander _Comment installer l'agent de la console NetApp sans Internet ?_ essayez :
+
--
[]
====
Quelles étapes dois-je suivre pour installer l’agent NetApp Console sans Internet ?

====
--
Divisez les questions complexes en blocs.:: Divisez les questions complexes en questions plus petites (également appelées _chaînage_). Doc se souvient des questions précédentes et crée des réponses plus complexes pendant que vous continuez à discuter.
+
--
Par exemple, au lieu de demander au Doc « Comment configurer la protection contre les ransomwares et les planifications de sauvegarde dans la console NetApp ? », essayez :

[]
====
Quelles sont les étapes à suivre pour configurer la protection contre les ransomwares dans la console NetApp ?

====
puis demander :

[]
====
Quelles sont les étapes à suivre pour configurer les planifications de sauvegarde dans la console NetApp ?

====
--
Utiliser des guillemets.:: Placez des expressions à plusieurs mots entre guillemets. Cela permet à Doc de reconnaître l'expression comme un concept unique, semblable à la façon dont vous pourriez l'insister dans une conversation avec un humain.
+
--
Par exemple, dans cette question, _Comment l'efficacité du stockage est-elle calculée dans ONTAP ?_ Doc peut-être pensez-vous vous poser la question du _stockage_ et de l'efficacité_ comme deux mots sans rapport. Essayez plutôt :

[]
====
Comment l'efficacité du stockage est-elle calculée dans ONTAP ?

====
--
Passez en revue la réponse de Doc.:: Après avoir répondu, Doc fournit des informations sur la façon dont il a généré sa réponse. Cela peut vous donner des idées pour affiner votre question afin d'obtenir les résultats que vous voulez.
Effacer l'historique de vos discussions:: Si vous souhaitez changer de sujet (par exemple, pour poser une question sur un autre produit), effacez l'historique de discussion pour démarrer une nouvelle session. Si vous ne effacez pas l'historique de discussion avant de démarrer une nouvelle discussion, vous risquez d'obtenir des résultats erronés.




== Commentaires

Nous nous efforçons d'améliorer continuellement le document Veuillez nous envoyer vos commentaires dans la fenêtre de discussion de Doc. Dites-nous si les réponses de Doc sont exactes et utiles ou si elles sont incomplètes ou insuffisantes. Vous pouvez également mailto:ng-doccomments@netapp.com[nous contacter] si vous avez des questions ou des préoccupations concernant les capacités ou les réponses de Doc.
