---
sidebar: sidebar 
permalink: doc-gen-ai-assistant.html 
keywords: netapp, generative ai, doc 
summary: 'Doc est l"assistant NetApp ai disponible sur docs.NetApp.com. Il répond aux questions en utilisant uniquement le contenu de ce site. Doc n"utilise pas de contenu provenant d"autres sites NetApp ou d"Internet public pour répondre aux questions.' 
---
= Présentation de l'assistant génératif NetApp optimisé par l'IA
:hardbreaks:
:allow-uri-read: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Doc est l'assistant NetApp ai disponible sur docs.NetApp.com. Il répond aux questions en utilisant uniquement le contenu de ce site. Doc n'utilise pas de contenu provenant d'autres sites NetApp ou d'Internet public pour répondre aux questions.

Le DOC peut créer des réponses à partir de questions précédentes, suggérer des questions supplémentaires et expliquer comment il génère des réponses. Cela en fait un outil précieux pour naviguer dans la documentation NetApp.



== Portée et limites

Doc ne peut répondre qu'aux questions en fonction du contenu publié sur docs.NetApp.com.


NOTE: Au cours de cette phase bêta, Doc n'est pas formé sur tout le contenu docs.NetApp.com. Doc peut répondre à des questions sur le contenu, y compris, mais sans s'y limiter, le contenu ONTAP, BlueXP , StorageGRID, Keystone et SnapCenter. Si vous avez besoin d'information Doc n'a pas, faites-le nous savoir.

* Doc répond aux questions en se basant uniquement sur la dernière version publiée d'un produit. Par exemple, s'il existe une documentation pour les versions 1.0 et 2.0 d'un produit, Doc se réfère uniquement à la documentation 2.0 la plus récente.
* Pour de meilleurs résultats, soyez toujours précis dans les noms de produits. Doc sait sur quelle page vous vous trouvez lorsque vous posez une question, mais ce n'est qu'un facteur parmi d'autres qu'il prend en compte pour formuler une réponse.
* Doc peut discuter dans les langues prises en charge sur docs.NetApp.com, mais n'est pas formé sur les versions non anglaises.




== Rédaction de bons messages-guides

Suivez ces conseils pour une expérience optimale avec Doc

Posez des questions spécifiques.:: Rédigez des questions détaillées et spécifiez le nom du produit, la version et le type d'interface (interface graphique, API). Par exemple :
+
--
[]
====
Quelles étapes dois-je suivre dans System Manager pour effectuer la mise à niveau de ONTAP 9.8 vers ONTAP 9.12.1 ?

====
--
Demandez des étapes pour effectuer une tâche.:: Demandez à Doc d'inclure les étapes pour terminer un processus. Au lieu de demander _Comment installer le connecteur BlueXP  sans Internet?_ essayez :
+
--
[]
====
Quelles étapes dois-je suivre pour installer BlueXP  Connector sans Internet ?

====
--
Divisez les questions complexes en blocs.:: Divisez les questions complexes en questions plus petites (également appelées _chaînage_). Doc se souvient des questions précédentes et crée des réponses plus complexes pendant que vous continuez à discuter.
+
--
Par exemple, au lieu de vous poser la question suivante : « Comment configurer la protection contre les ransomwares et les plannings de sauvegarde dans BlueXP  ?_ essayez :

[]
====
Quelles sont les étapes de configuration de la protection contre les ransomwares dans BlueXP  ?

====
puis demander :

[]
====
Quelles sont les étapes de configuration des plannings de sauvegarde dans BlueXP  ?

====
--
Utiliser des guillemets.:: Placez des expressions à plusieurs mots entre guillemets. Cela permet à Doc de reconnaître l'expression comme un concept unique, semblable à la façon dont vous pourriez l'insister dans une conversation avec un humain.
+
--
Par exemple, dans cette question, _Comment l'efficacité du stockage est-elle calculée dans ONTAP ?_ Doc peut-être pensez-vous vous poser la question du _stockage_ et de l'efficacité_ comme deux mots sans rapport. Essayez plutôt :

[]
====
Comment l'efficacité du stockage est-elle calculée dans ONTAP ?

====
--
Passez en revue la réponse de Doc.:: Après avoir répondu, Doc fournit des informations sur la façon dont il a généré sa réponse. Cela peut vous donner des idées pour affiner votre question afin d'obtenir les résultats que vous voulez.
Effacer l'historique de vos discussions:: Si vous souhaitez modifier des rubriques, supprimez la discussion dès le début. Comme Doc se souvient des questions précédentes, les changements de sujet peuvent produire des résultats inattendus.




== Commentaires

Vos commentaires nous aideront à améliorer la réponse de Doc. Utilisez l'outil de commentaires de la fenêtre de discussion Doc pour nous indiquer si les réponses sont exactes et utiles ou si elles ont besoin d'amélioration. Vous pouvez également envoyer à mailto:ng-doccommentaires@NetApp.com[nous contacter] si vous avez des questions ou des commentaires.
