---
jekyll: srd23-stable-12
settings:
  name: About docs.netapp.com
  internal:
    pdf_enabled: false
  prod:
    pdf_enabled: false
    harmony_enabled: false
  langs: fr-fr,us-en,ja-jp,ko-kr,zh-cn,zh-tw,de-de,es-es,it-it
sidebar:
  entries:
  - title: À propos des sites
    url: "/docs-netapp-com.html"
  - title: Mentions légales
    url: "/legal-notices.html"
